### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Mornnn** [SydCaption/SAAT#40]
Hello, I encountered the following issues while reproducing your code：
2023-11-13 20:39:51,679:INFO: Testing time: 0:09:02.236245
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7fbb43bfdf60>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7fbb3b3e5c18>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7fbb3b2bf9b0>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
TypeError: 'NoneType' object is not callable

**Comment by Mornnn** [comment]
and this question：
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7f501957ee48>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7f4fb0f53ac8>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method DataLoader.__del__ of <dataloader_svo.DataLoader object at 0x7f4fb0e2c860>>
Traceback (most recent call last):
  File "/media/yy/Yy/videoCaption/SAAT-master/dataloader_svo.py", line 99, in __del__
  File "/home/yy/anaconda3/envs/SAAT/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
